### 사진있는리뷰 생성
POST http://localhost:8080/photo-reviews
Content-Type: application/json

{
  "score": 5,
  "content": "테스트1테스트1테스트테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트11테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1테스트1",
  "clientId": 1,
  "orderDetailId": 1,
  "photoUrls": [
    "http://localhost:8080/img/sample_images_00.png"
  ]
}

### 사진있는리뷰 단건조회
GET http://localhost:8080/photo-reviews/1
Content-Type: application/json

### 사진있는리뷰 전체조회
GET http://localhost:8080/photo-reviews
Content-Type: application/json

### 사진있는리뷰 수정
PUT http://localhost:8080/photo-reviews/1
Content-Type: application/json

{
  "score": 3,
  "content": "테스트2",
  "clientId": 1,
  "orderDetailId": 1,
  "photoUrls": [
    "http://localhost:8080/img/sample_images_00.png",
    "http://localhost:8080/img/sample_images_01.png",
    "http://localhost:8080/img/sample_images_02.png",
    "http://localhost:8080/img/sample_images_03.png"
  ]
}

### 사진있는리뷰 삭제
DELETE http://localhost:8080/photo-reviews/1
Content-Type: application/json

